[theme]
primaryColor="#2870f3"
#primaryColor="#0e2a4e"
#backgroundColor="#def1ff"
backgroundColor="#F3F6FB"

#secondaryBackgroundColor="#9bd7f9"
secondaryBackgroundColor="#98B2E0"


textColor="#000000"
